### ISSUE TITLE
Last.fm plugin does not handle unicode payload

### ISSUE THREAD

**Issue by jesseward** [MediaBrowser/Last.fm#12]
```2019-10-27 13:45:06.538 Info SessionManager: Playback start reported by app Emby Web 4.3.0.15 playing 日出ズル Style. Started at 0 ms
2019-10-27 13:45:06.544 Info HttpClient: POST http://ws.audioscrobbler.com/2.0/?format=json
2019-10-27 13:45:06.544 Info HttpServer: HTTP Response 204 to 172.17.0.1. Time: 7ms. http://localhost:8096/emby/Sessions/Playing
2019-10-27 13:45:06.548 Info HttpServer: HTTP GET http://localhost:8096/emby/Users/9df88eb886aa41c18973640efcfdda26/Items/10. UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
2019-10-27 13:45:06.549 Info HttpServer: HTTP GET http://localhost:8096/emby/Items/6/Images/Primary?height=70&tag=66005f194144b0b697070fb6e8ade611&quality=90. UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
2019-10-27 13:45:06.551 Info HttpServer: HTTP Response 200 to 172.17.0.1. Time: 3ms. http://localhost:8096/emby/Users/9df88eb886aa41c18973640efcfdda26/Items/10
2019-10-27 13:45:06.604 Info HttpServer: HTTP Response 200 to 172.17.0.1. Time: 54ms. http://localhost:8096/emby/Items/6/Images/Primary?height=70&tag=66005f194144b0b697070fb6e8ade611&quality=90
2019-10-27 13:45:06.633 Error Last.fm: Failed to send now playing for track: 日出ズル Style
	*** Error Report ***
	Version: 4.3.0.15
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.9.184.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///system/System.Private.CoreLib.dll
	Processor count: 4
	Program data path: /config
	Application directory: /system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: BadRequest
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Lastfm.Api.BaseLastfmApiClient.Post[TRequest,TResponse](TRequest request)
	   at Lastfm.Api.LastfmApiClient.NowPlaying(Audio item, LastfmUser user)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
```

**Comment by jesseward** [comment]
Last.FM spec (https://www.last.fm/api/authspec#8) suggests that we should `Ensure your parameters are utf8 encoded.`

```diff
diff --git a/Lastfm/Utils/Helpers.cs b/Lastfm/Utils/Helpers.cs
index 1035605..14e762b 100644
--- a/Lastfm/Utils/Helpers.cs
+++ b/Lastfm/Utils/Helpers.cs
@@ -16,7 +16,7 @@
             // Use input string to calculate MD5 hash
             var md5 = MD5.Create();

-            var inputBytes = Encoding.ASCII.GetBytes(input);
+            var inputBytes = Encoding.UTF8.GetBytes(input);
             var hashBytes  = md5.ComputeHash(inputBytes);

             // Convert the byte array to hexadecimal string
```

**Comment by jesseward** [comment]
created 1.0.21.0 with above fix 
```
2019-10-27 13:56:40.908 Info App: Loading Lastfm, Version=1.0.21.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Lastfm.dll
2019-10-27 13:57:14.009 Info Last.fm: jw76 is now playing '日出ズル Style' - Samurai Champloo Music Record - Impression - Force of Nature
2019-10-27 13:57:40.923 Info HttpClient: POST http://ws.audioscrobbler.com/2.0/?format=json
2019-10-27 13:57:41.032 Info Last.fm: jw76 played '日出ズル Style' - Samurai Champloo Music Record - Impression - Force of Nature
```

**Comment by jesseward** [comment]
merged in https://github.com/MediaBrowser/Last.fm/pull/13
