### ISSUE TITLE
Null values for MbId or Album (System.ArgumentNullException: Value cannot be null)

### ISSUE THREAD

**Issue by jesseward** [MediaBrowser/Last.fm#5]
Recent changes have introduced the ability to send both `request.mbid` and `request.album` for now playing and scrobbling actions. This triggers a bug when either of these are *not set*. These will fall back to  their default values (null), and then passed into 
 `Lastfm.Api.BaseLastfmApiClient.EscapeDictionary` . 

Resulting in the following

```2019-03-17 07:05:41.559 Error Last.fm: Failed to Scrobble track: Les Nuits (NOW Mix)
        *** Error Report ***
        Version: 4.1.0.15
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Unix 4.18.20.0
        64-Bit OS: True
        64-Bit Process: True
        User Interactive: True
        Processor count: 4
        Program data path: /config
        Application directory: /system
        System.ArgumentNullException: System.ArgumentNullException: Value cannot be null.
        Parameter name: stringToEscape
           at System.Uri.EscapeDataString(String stringToEscape)
           at Lastfm.Api.BaseLastfmApiClient.<>c.<EscapeDictionary>b__9_1(KeyValuePair`2 item)
           at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
           at Lastfm.Api.BaseLastfmApiClient.EscapeDictionary(Dictionary`2 dic)
           at Lastfm.Api.BaseLastfmApiClient.Post[TRequest,TResponse](TRequest request)
           at Lastfm.Api.LastfmApiClient.Scrobble(Audio item, LastfmUser user)
        Source: System.Private.Uri
        TargetSite: System.String EscapeDataString(System.String)```

**Comment by jesseward** [comment]
I have logged https://github.com/MediaBrowser/Last.fm/pull/6 , which provides a simple fix that involves filtering/removing any key from the dictionary where its value is null (or whitespace). The dict is updated before passed to the `CreateSignature` method and any subsequent method that relies on the Request data.

```
2019-03-18 06:12:34.992 Info Last.fm: jw76 is now playing 'Les Nuits (NOW Mix)' - Les Nuits - Nightmares On Wax
2019-03-18 06:12:43.259 Info HttpServer: HTTP POST http://192.168.86.254:8096/emby/Sessions/Playing/Progress. UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
```

for `track.scrobble` (https://www.last.fm/api/show/track.scrobble) and `track.updateNowPlaying` both   last.fm API fields mbid and album are denoted as optional (https://www.last.fm/api). So the POST is still functional without.

**Comment by jesseward** [comment]
Looks like this was fixed in https://github.com/MediaBrowser/Last.fm/pull/7/files
